version: "3"
services:
       sub-project:
           container_name: cloud_storage
           image: sub-project
           restart: always
           build: .
          #  environment:
          #    MONGO_URL: 'mongodb://mongo:27017'
           ports:
             - "5200:5200"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'